In [23]:
import pandas as pd
import numpy as np

# Used Car Price Prediction

## Project Overview

The objective of this project is to build a machine learning model capable of predicting the resale price of used vehicles based on their intrinsic characteristics. The notebook follows a structured workflow consisting of data inspection, preprocessing, exploratory data analysis (EDA), feature engineering, and model development.

This notebook focuses on understanding the dataset, improving data quality, and preparing the features for predictive modeling.

In [24]:
df=pd.read_csv(r"C:\Users\shash\Downloads\dataset.txt")

In [25]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
display(df.head())
display(df.sample(5))

Shape: (426880, 26)
Columns: ['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer', 'model', 'condition', 'cylinders', 'fuel', 'odometer', 'title_status', 'transmission', 'VIN', 'drive', 'size', 'type', 'paint_color', 'image_url', 'description', 'county', 'state', 'lat', 'long', 'posting_date']

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,7222270760,https://worcester.craigslist.org/cto/d/west-br...,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
379170,7304731438,https://mcallen.craigslist.org/cto/d/san-juan-...,mcallen / edinburg,https://mcallen.craigslist.org,17899,2018.0,dodge,charger,like new,8 cylinders,...,mid-size,sedan,black,https://images.craigslist.org/00000_hz7j8A2lJB...,🟢⚪️🔴🟢⚪️🔴🟢⚪️🔴🟢⚪️🔴🟢 🔥2018 DODGE CHARGER R/T🔥 🚘🚘...,NaN,tx,26.177100,-98.187000,2021-04-10T11:42:18-0500
251942,7306635525,https://cnj.craigslist.org/ctd/d/trenton-2019-...,central NJ,https://cnj.craigslist.org,33990,2019.0,lincoln,nautilus select sport,good,NaN,...,NaN,other,white,https://images.craigslist.org/00S0S_kZRjoBUgLd...,Carvana is the safer way to buy a car During t...,NaN,nj,40.220000,-74.760000,2021-04-14T10:11:14-0400
261003,7312291664,https://albuquerque.craigslist.org/ctd/d/edgew...,albuquerque,https://albuquerque.craigslist.org,31422,2012.0,chevrolet,silverado 2500hd,NaN,NaN,...,NaN,NaN,NaN,https://images.craigslist.org/00404_gYlOs5yTmQ...,Tillery Chevrolet GMC address: PO Box 609 ...,NaN,nm,35.004363,-106.049794,2021-04-25T07:47:52-0600
259967,7314920512,https://albuquerque.craigslist.org/ctd/d/albuq...,albuquerque,https://albuquerque.craigslist.org,0,2016.0,chevrolet,colorado crew cab 4wd,good,6 cylinders,...,mid-size,truck,grey,https://images.craigslist.org/00000_gNzYtCo76m...,2016 Chevrolet Colorado Crew Cab Z-71 4WD V6 h...,NaN,nm,35.144776,-106.586276,2021-04-30T12:08:34-0600
65050,7311766822,https://stockton.craigslist.org/ctd/d/atlanta-...,stockton,https://stockton.craigslist.org,35590,2019.0,honda,ridgeline rtl-t pickup 4d,good,NaN,...,NaN,pickup,black,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,NaN,ca,33.786500,-84.445400,2021-04-24T03:35:36-0700

In [ ]:
df.describe()

## Feature Selection

To improve model generalization and remove non-informative attributes, 
several columns were excluded from the dataset. These features were either unique identifiers
 URLs, location-specific information, or unstructured text that were not relevant for this tabular machine learning project.

| Column | Reason for Removal |
|---------|--------------------|
| `id` | Unique identifier with no predictive value. |
| `url` | Listing URL; not useful for prediction. |
| `region_url` | Region webpage URL; irrelevant for ML. |
| `image_url` | Image link not used in tabular ML. |
| `VIN` | Unique vehicle identifier; high-cardinality feature. |
| `description` | Free-text column requiring NLP; excluded from this project. |
| `state` | Removed to build a location-independent model. |
| `region` | Location-specific feature removed for better generalization. |
| `lat` | Geographic coordinate removed to avoid location bias. |
| `long` | Geographic coordinate removed to avoid location bias. |
| `posting_date` | Listing timestamp not directly related to vehicle characteristics. |

In [27]:
df.drop(columns=["id","url","region_url","VIN","image_url","description","county","state","lat","long","posting_date","region"],inplace=True)

In [ ]:
print(df.shape)
display(df.head())

## Feature Renaming

To improve readability, consistency, and maintainability, several feature names were renamed to more descriptive names. This naming convention makes the dataset easier to understand and improves the overall quality of the machine learning pipeline.

| Original Feature | Renamed Feature | Reason |
|------------------|-----------------|--------|
| `fuel` | `fuel_type` | Clearly specifies the type of fuel used by the vehicle. |
| `odometer` | `distance_driven_km` | Indicates the total distance travelled by the vehicle in kilometers. |
| `title_status` | `vehicle_title_status` | Provides a more descriptive name for the vehicle's legal ownership status. |
| `transmission` | `transmission_type` | Clearly indicates the type of transmission (Automatic or Manual). |
| `drive` | `drive_type` | Clarifies the drivetrain configuration (FWD, RWD, 4WD, AWD). |
| `size` | `vehicle_size` | Explicitly represents the vehicle's size category. |
| `type` | `vehicle_type` | Avoids confusion with Python's built-in `type()` function and clearly represents the vehicle category. |
| `cylinders` | `number_of_cylinders` | Clearly indicates the total number of engine cylinders in the vehicle. |

In [28]:
df.rename(columns={
    "fuel": "fuel_type",
    "odometer": "distance_driven_km",
    "title_status": "vehicle_title_status",
    "drive": "drive_type",
    "size": "vehicle_size",
    "type": "vehicle_type",
    "cylinders": "number_of_cylinders",
    "transmission": "transmission_type"
}, inplace=True)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   price                 426880 non-null  int64
 1   year                  425675 non-null  float64
 2   manufacturer          409234 non-null  str
 3   model                 421603 non-null  str
 4   condition             252776 non-null  str
 5   number_of_cylinders   249202 non-null  str
 6   fuel_type             423867 non-null  str
 7   distance_driven_km    422480 non-null  float64
 8   vehicle_title_status  418638 non-null  str
 9   transmission_type     424324 non-null  str
 10  drive_type            296313 non-null  str
 11  vehicle_size          120519 non-null  str
 12  vehicle_type          334022 non-null  str
 13  paint_color           296677 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 45.6 MB

In [ ]:

# currently we can"t convert year column to integer datatype as there are many missing values

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   price                 426880 non-null  float64
 1   year                  425675 non-null  float64
 2   manufacturer          409234 non-null  str
 3   model                 421603 non-null  str
 4   condition             252776 non-null  str
 5   number_of_cylinders   249202 non-null  str
 6   fuel_type             423867 non-null  str
 7   distance_driven_km    422480 non-null  float64
 8   vehicle_title_status  418638 non-null  str
 9   transmission_type     424324 non-null  str
 10  drive_type            296313 non-null  str
 11  vehicle_size          120519 non-null  str
 12  vehicle_type          334022 non-null  str
 13  paint_color           296677 non-null  str
dtypes: float64(3), str(11)
memory usage: 45.6 MB

## Target Leakage Assessment

To ensure the model learns genuine relationships rather than relying on information unavailable during real-world prediction, a target leakage assessment was performed.

The assessment included:

- Verifying that all retained features are available before the selling price is known.
- Removing unique identifiers, URLs, image links, and other non-predictive attributes.
- Reviewing feature definitions to ensure no variable directly or indirectly reveals the target.

Based on these checks, no obvious source of target leakage was identified in the final feature set.